FROM python:3.9.5-buster

ENV PYTHONUNBUFFERED 1

WORKDIR /code

COPY Pipfile Pipfile
COPY Pipfile.lock Pipfile.lock

RUN pip install --upgrade pip \
    && pip install pipenv \
    && pipenv install --system --deploy --ignore-pipfile --clear

COPY ./app .

CMD ["celery", "-A", "planeks", "worker", "--loglevel=INFO", "-Q", "generator"]
