version: '3'

services:
    postgres:
        container_name: planeks_postgres
        image: postgres:12 # TODO: check this version later, may be heroku supports 13
        restart: 'always'
        volumes:
            - planeks-postgres:/var/lib/postgresql/data
        env_file: .env
        networks:
            - planeks-app-network

    redis:
        container_name: planeks_redis
        image: redis:5 # TODO: check this version later, may be heroku supports 6
        restart: 'always'
        env_file: .env
        volumes:
            - planeks-redis:/var/lib/redis
        networks:
            - planeks-app-network

networks:
    planeks-app-network:
        driver: bridge

volumes:
    planeks-postgres:
    planeks-redis:
