version: '3'

services:
    postgres:
        container_name: planeks_postgres
        image: postgres:12 # TODO: check this version later, may be heroku supports 13
        restart: 'always'
        volumes:
            - planeks-postgres:/var/lib/postgresql/data
        env_file: .env
        networks:
            - planeks-app-network

    redis:
        container_name: planeks_redis
        image: redis:5 # TODO: check this version later, may be heroku supports 6
        restart: 'always'
        env_file: .env
        volumes:
            - planeks-redis:/var/lib/redis
        networks:
            - planeks-app-network

    app:
        container_name: planeks_app
        build:
            context: .
            dockerfile: Dockerfile.app
        restart: 'always'
        env_file: .env
        volumes:
            - planeks-media:/code/media
        networks:
            - planeks-app-network
        ports:
            - '80:80'
        depends_on:
            - postgres

    celery:
        container_name: planeks_celery
        build:
            context: .
            dockerfile: Dockerfile.celery
        restart: 'always'
        env_file: .env
        volumes:
            - planeks-media:/code/media
        networks:
            - planeks-app-network
        command: celery -A planeks worker --loglevel=INFO -Q generator
        depends_on:
            - redis

networks:
    planeks-app-network:
        driver: bridge

volumes:
    planeks-postgres:
    planeks-redis:
    planeks-media:
