# This override compose file does the following
#   * Exposes ports for local development

services:
    postgres:
        ports:
            - '5432:5432'

    redis:
        ports:
            - '6379:6379'
