# Generated by Django 3.2.2 on 2021-05-07 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataschemas', related_query_name='dataschema', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('fn', 'Full name'), ('jb', 'Job title'), ('em', 'Email address'), ('do', 'Domain name'), ('pn', 'Phone number'), ('cn', 'Company name'), ('te', 'Text'), ('in', 'Integer number'), ('ad', 'Address'), ('da', 'Date')], max_length=2)),
                ('range_from', models.IntegerField(blank=True, null=True)),
                ('range_to', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', related_query_name='column', to='dataschemas.dataschema')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dataschema',
            constraint=models.UniqueConstraint(fields=('title', 'user'), name='unique_title_for_user'),
        ),
        migrations.AddConstraint(
            model_name='datacolumn',
            constraint=models.UniqueConstraint(fields=('title', 'schema'), name='unique_column_for_schema'),
        ),
    ]
