# Generated by Django 3.2.2 on 2021-05-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataschemas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacolumn',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
